controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

export_users:
    path: /export-users
    controller: App\Controller\UserController::exportUsers

